# Change these first
# Upptime 支援使用預設環境變數自動取得 owner 與 repo
owner: $OWNER
repo: $REPO

sites:
  - name: $S1N
    url: $S1U
  - name: $S2N
    url: $S2U
  - name: $S3N
    url: $S3U
  - name: $S7N
    url: $S7U
  - name: $S4N
    url: $S4U
  - name: $S5N
    url: $S5U
  - name: $S6N
    url: $S6U
status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  cname: $STATUS_CNAME
  # baseUrl: /your-repo-name
  #logoUrl: $STATUS_LOGO_URL
  name: 書庫大廳
  introTitle: 幻書封印狀態總覽
  introMessage: "*「愚蠢的人類啊，想要窺探惡魔的智慧嗎？」*"
  navbar:
    - title: 幻書目錄
      href: /
    - title: 讀姬的手稿
      href: $STATUS_CNAME

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
