# Change these first
# Upptime 支援使用預設環境變數自動取得 owner 與 repo
owner: $OWNER
repo: $REPO

# 🔻 必須明確列出所有用到 Secret 變數名稱，GitHub Actions 才能順利讀取
secrets:
  - S1N
  - S1U
  - S2N
  - S2U
  - S3N
  - S3U
  - S4N
  - S4U
  - S5N
  - S5U
  - S6N
  - S6U
  - S7N
  - S7U
  - STATUS_CNAME

sites:
  - name: 主站
    url: $S1U
  - name: 日榜 API + D1
    url: $S2U
  - name: CDN / B2 Worker	
    url: $S3U
  - name: Cloudflare API
    url: $S4U
  - name: B2 S3 API
    url: $S5U
  - name: GitHub
    url: $S6U
  - name: Pixiv
    url: $S7U

status-website:
  # 如果沒有自訂網域，請將下面這行 cname 刪除或加 # 註解掉
  cname: noshoka.org
  # baseUrl: /your-repo-name
  # logoUrl: $STATUS_LOGO_URL
  name: 書庫大廳
  introTitle: 幻書封印狀態總覽
  introMessage: "*「愚蠢的人類啊，想要窺探惡魔的智慧嗎？」*"
  navbar:
    - title: 幻書目錄
      href: /
    - title: 讀姬的手稿
      href: https://noshoka.org
# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
